"""
Order type definitions — dataclass-based order models.

Refactored from legacy/order/order_definition.py.
"""

from dataclasses import dataclass, field, asdict
from enum import Enum


class OrderType(str, Enum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    SL = "SL"
    SL_M = "SL-M"


class TransactionType(str, Enum):
    BUY = "BUY"
    SELL = "SELL"


class ProductType(str, Enum):
    INTRADAY = "I"
    DELIVERY = "D"


class Validity(str, Enum):
    DAY = "DAY"
    IOC = "IOC"


@dataclass
class OrderRequest:
    """Order request that can be sent to Upstox API."""

    instrument_token: str
    quantity: int
    transaction_type: TransactionType
    order_type: OrderType = OrderType.MARKET
    product: ProductType = ProductType.DELIVERY
    validity: Validity = Validity.DAY
    price: float = 0.0
    trigger_price: float = 0.0
    disclosed_quantity: int = 0
    is_amo: bool = False
    slice: bool | None = None
    market_protection: int | None = None
    tag: str = "upstox-auto"

    def to_api_dict(self) -> dict:
        """Convert to the dict format expected by Upstox SDK."""
        return {
            "quantity": self.quantity,
            "product": self.product.value,
            "validity": self.validity.value,
            "price": self.price,
            "tag": self.tag,
            "instrument_token": self.instrument_token,
            "order_type": self.order_type.value,
            "transaction_type": self.transaction_type.value,
            "disclosed_quantity": self.disclosed_quantity,
            "trigger_price": self.trigger_price,
            "is_amo": self.is_amo,
            "slice": self.slice,
            "market_protection": self.market_protection,
        }


@dataclass
class TradeSignal:
    """Signal generated by a strategy."""

    action: TransactionType       # BUY or SELL
    instrument_key: str
    price: float                  # signal price
    stop_loss: float = 0.0
    take_profit: float = 0.0
    quantity: int = 0             # 0 = let risk manager decide
    strategy_name: str = ""
    timeframe: str = ""
    confidence_score: int = 0     # soft filter score
    metadata: dict = field(default_factory=dict)
